### ISSUE TITLE
[PE-D][Tester A] Overlap condition and with activation bar in Sequence Diagram

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W10-2/tp#312]
![Screenshot 2024-11-08 at 5.35.14 PM.png](https://raw.githubusercontent.com/AjayShanker-geek/ped/main/files/e8ccc578-95c9-47f8-a10e-86b7aa45e919.png)

The condition overlaps with activation bar making it difficulty to read the sequence diagram.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: AjayShanker-geek/ped#12

**Comment by louisjoety** [comment]
Trivial for now but I will check.
